#-------------------------------------------------------------------------------
# Variables used by the roles in my Libraries - Ansible repository
# See the README for that repository at:
# https://github.com/varilink/libraries-ansible#readme
# for documentation about these variables.
#-------------------------------------------------------------------------------

# Mandatory
# ---------

# All hosts on the external to office network (Internet) use a third-party DNS
# service, which we simulate here in this Docker container environment.
dns_resolvers: [10.0.0.105]
# All hosts that are external to the office network with the exception of the
# external mail server use the external mail server as a smarthost. The external
# mail server uses another services providers mail gateway server as a
# smarthost.
mta_smarthost:
  hostname: mail-external
  username: username1
  userpass: userpass1
