# ------------------------------------------------------------------------------
# envs/distributed/docker-compose.yml
# ------------------------------------------------------------------------------

# Host Docker Compose services for the distributed simulation environment.

version: "3.7"

services:

  backup-director:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_backup-director
    hostname: backup-director
    volumes:
      - director-bacula-home:/var/lib/bacula/
    networks:
      default:
        ipv4_address: 10.0.0.101

  backup-storage:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_backup-storage
    hostname: backup-director
    volumes:
      - storage-bacula-home:/var/lib/bacula/
    networks:
      default:
        ipv4_address: 10.0.0.102

  caldav:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_caldav
    hostname: caldav
    networks:
      default:
        ipv4_address: 10.0.0.103

  database-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_database-external
    hostname: database-external
    networks:
      default:
        ipv4_address: 10.0.0.104

  database-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_database-internal
    hostname: database-internal
    networks:
      default:
        ipv4_address: 10.0.0.105

  dns-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dns-external
    hostname: dns-external
    networks:
      default:
        ipv4_address: 10.0.0.106

  dns-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dns-internal
    hostname: dns-internal
    networks:
      default:
        ipv4_address: 10.0.0.107

  dynamic-dns:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dynamic-dns
    hostname: dynamic-dns
    networks:
      default:
        ipv4_address: 10.0.0.108

  mail-certificates:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_mail-certificates
    hostname: mail-certificates
    networks:
      default:
        ipv4_address: 10.0.0.109

  mail-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_mail-external
    hostname: mail-external
    networks:
      default:
        ipv4_address: 10.0.0.110

  mail-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    hostname: mail-internal
    container_name: services_mail-internal
    networks:
      default:
        ipv4_address: 10.0.0.111

  reverse-proxy-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-external
    hostname: reverse-proxy-external
    networks:
      default:
        ipv4_address: 10.0.0.112

  reverse-proxy-gateway:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-gateway
    hostname: reverse-proxy-gateway
    networks:
      default:
        ipv4_address: 10.0.0.113

  reverse-proxy-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-internal
    hostname: reverse-proxy-internal
    networks:
      default:
        ipv4_address: 10.0.0.114

  wordpress-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_wordpress-external
    hostname: wordpress-external
    networks:
      default:
        ipv4_address: 10.0.0.115

  wordpress-internal:
    build: build/sshd
    container_name: services_wordpress-internal
    image: varilink/services/ssh:bullseye
    hostname: wordpress-internal
    networks:
      default:
        ipv4_address: 10.0.0.116

volumes:
  director-bacula-home:
  storage-bacula-home:
