# ------------------------------------------------------------------------------
# envs/now/docker-compose.yml
# ------------------------------------------------------------------------------

# Host Docker Compose services for the "now" test environment.

version: "3.7"

services:

  # office network

  dev:
    build:
      context: build/sshd
      args:
        RELEASE: buster
    image: varilink/services/sshd:buster
    container_name: services_dev
    hostname: dev
    networks:
      office:
        ipv4_address: 10.0.0.101
    cap_add:
      - NET_ADMIN

  gateway:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_gateway
    hostname: gateway
    networks:
      office:
        ipv4_address: 10.0.0.102
    cap_add:
      - NET_ADMIN

  home:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_home
    hostname: home
    networks:
      office:
        ipv4_address: 10.0.0.103
    cap_add:
      - NET_ADMIN

  hub:
    build:
      context: build/sshd
      args:
        RELEASE: buster
    image: varilink/services/sshd:buster
    container_name: services_hub
    hostname: hub
    volumes:
      - bacula-home:/var/lib/bacula/
    networks:
      office:
        ipv4_address: 10.0.0.104
    cap_add:
      - NET_ADMIN

  # internet

  dns-external:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_dns-external
    hostname: dns-external
    networks:
      internet:
        ipv4_address: 10.0.1.101
    cap_add:
      - NET_ADMIN

  prod1:
    build:
      context: build/sshd
      args:
        RELEASE: stretch
    image: varilink/services/sshd:stretch
    container_name: services_prod1
    hostname: prod1
    volumes:
      - ./envs/now/sources.list:/etc/apt/sources.list
    networks:
      internet:
        ipv4_address: 10.0.1.102
    cap_add:
      - NET_ADMIN

  prod4:
    build:
      context: build/sshd
      args:
        RELEASE: bullseye
    image: varilink/services/sshd:bullseye
    container_name: services_prod4
    hostname: prod4
    networks:
      internet:
        ipv4_address: 10.0.1.103
    cap_add:
      - NET_ADMIN

volumes:
  bacula-home:
