# ------------------------------------------------------------------------------
# envs/live/playbooks/home/group_vars/all.yml
# ------------------------------------------------------------------------------

---

domain_name: home.com
domain_organisation: Home Organisation
domain_country: GB
domain_state: Derbyshire
domain_locality: Long Eaton
domain_users:
  - fname: user1fname
    lname: user1lname
  - fname: user2fname
    lname: user2lname
    password: 't7515%8*MixUyR7o'
wordpress_site_reverse_proxy_pass_port: 8082
