- ansible.builtin.import_role:
    name: my_dns
    tasks_from: none
  delegate_to: "\
    {{ wordpress_site_dns_host | default(inventory_hostname) }}"

- ansible.builtin.import_role:
    name: my_reverse_proxy
    tasks_from: none
  delegate_to: "\
    {{ wordpress_site_reverse_proxy_host | default(inventory_hostname) }}"

- ansible.builtin.import_role:
    name: wordpress_apache
    tasks_from: create-sites
