# ------------------------------------------------------------------------------
# my-roles/my_wordpress_apache/tasks/start-apache.yml
# ------------------------------------------------------------------------------

---

- name: Test if the apache2 process is running
  ansible.builtin.shell: |-
    pgrep -f '^apache2 -D FOREGROUND$' || true
  register: pgrep_result
  changed_when: false

- name: Start the apache2 process
  ansible.builtin.shell: |-
    source /etc/apache2/envvars

    echo 'apache2    : Starting' >> '/var/local/services.log'
    nohup apache2 -D FOREGROUND 2>&1 | sed 's/^/apache2    : /' \
      >> '/var/local/servies.log' &

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f '^apache2 -D FOREGROUND$' && \
        echo 'apache2    : Started' >> '/var/local/services.log' && break
      let n=n+1
    done

    if [ $n -eq 3 ]; then
      echo 'apache2    : Failed to start process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: not pgrep_result.stdout
