# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

version: "3.7"

networks:

  # We use the IPAM driver to allocate a subnet. Service hosts are then
  # allocated fixed IP addresses from 10.0.0.101 and test clients are allowed to
  # pick up dynamically allocated IP addresses from the Docker DHCP service.

  # The service hosts simulate a hybird server estate, combining on-premise or
  # office hosted servers (internal) with servers provided by our Cloud, virtual
  # server hosting provider (external). We don't simulate that network
  # separation in this Docker Compose project, as to do so would add complexity
  # without serving any practical purpose.

  office:
    ipam:
      config:
        - subnet: 10.0.0.0/24

  internet:
    ipam:
      config:
        - subnet: 10.0.1.0/24

services:

  # Docker Compose services that are used to create and bring up the Docker
  # Compose services that emulate hosts in our server estate and deploy
  # application services to them using Ansible.

  raise-hosts:
    # Outputs the required dockker and docker-compose commands to bring up the
    # host emulation Docker Compose services for an environment. These commands
    # are piped into a shell to execute them.
    build: ./build/raise-hosts
    environment:
      - MYENV
    network_mode: none
    volumes:
      - ./envs/${MYENV}/services-to-hosts.sh:/usr/src/services-to-hosts.sh

  playbook:
    # Runs the Ansible playbooks that deploy our application services to the
    # host emulation Docker containers for each environment.
    build: ./build/playbook
    environment:
      - MYENV
    volumes:
      # The configuration for the environment we're currently using, which could
      # be one of "now", "to-be" or "distributed".
      - ./envs/${MYENV}:/environment
      # The Varilink library of Ansible roles for our host services.
      - ./libraries-ansible:/libraries-ansible
      # A wrapper set of roles that bespoke the Varilink library of Ansible
      # roles for use with Docker containers.
      - ./my-roles:/my-roles
    networks:
      office:
    cap_add:
      - NET_ADMIN

  router:
    build: ./build/router
    networks:
      internet:
        ipv4_address: 10.0.1.254
      office:
        ipv4_address: 10.0.0.254

  # Docker Compose services that provide clients that can be used to test the
  # function of the application services that are deployed using Ansible to the
  # hosts in an environment.

  bconsole:
    build: ./build/bconsole
    env_file:
      - ./envs/${MYENV}/test/network.env
    volumes:
      - ./envs/${MYENV}/test/bconsole.conf:/etc/bacula/bconsole.conf

  cadaver:
    build: ./build/cadaver
    env_file:
      - ./envs/${MYENV}/test/network.env

  dig:
    build: ./build/dig
    env_file:
      - ./envs/${MYENV}/test/network.env

  lynx:
    build: ./build/lynx
    env_file:
      - ./envs/${MYENV}/test/network.env

  mutt:
    build: ./build/mutt
    env_file:
      - ./envs/${MYENV}/test/network.env
    volumes:
      - ./envs/${MYENV}/test/mutt;/config

  openssl:
    build: ./build/openssl
    env_file:
      - ./envs/${MYENV}/test/network.env

  proxy-internal:
    build: ./build/proxy
    env_file:
      - ./envs/${MYENV}/test/network.env
    command: internal
    ports:
      - "3128:3128"
    networks:
      office:
    cap_add:
      - NET_ADMIN

  proxy-external:
    build: ./build/proxy
    env_file:
      - ./envs/${MYENV}/test/network.env
    command: external
    ports:
      - "3129:3128"
    networks:
      internet:
    cap_add:
      - NET_ADMIN

  swaks:
    build: ./build/swaks
    env_file:
      - ./envs/${MYENV}/test/network.env
