---

# Deploy a project domain. There can be three aspects to this:
# 1. Dynamic DNS
# 2. Mail service
# 3. Web services
# Web services is plural because there may be multiple webhosts for a domain;
# for example dev (development), test and www (live).

# 1. Dynamic DNS
# --------------

# Plays to maintain required dynamic DNS entries

- hosts: dynamic-dns
  tags: dynamic_dns
  tasks:
    - ansible.builtin.include_vars:
        dir: "domains/{{ domain_name }}"
        name: domain

- hosts: dynamic-dns
  become: yes
  tags: dynamic_dns
  tasks:

    - name:
      ansible.builtin.copy:
        content: "{{ domain_dynamic_dns | to_nice_yaml }}"
        dest: "/usr/local/etc/dynamic-dns-domains/{{ domain.name }}.yml"
      vars:
        - domain_dynamic_dns:
            id: "{{ domain.linode_domain_id }}"
            records: "{{ domain.linode_dynamic_dns_domain_records }}"

# 2. Mail
# -------

# Plays for the mail service

- hosts: "\
    dns-external:dns-internal:mail-certificates:mail-external:mail-internal\
    "
  tags: mail
  tasks:
    - ansible.builtin.include_vars:
        dir: "domains/{{ domain_name }}"
        name: domain

- hosts: dns-external
  tags: mail
  roles:
    - role: domain_dns
      vars:
        mail_server_address: 10.0.0.109
        dns_scope: external

- hosts: dns-internal
  tags: mail
  roles:
    - role: domain_dns
      vars:
        mail_server_address: 10.0.0.110
        dns_scope: internal

- hosts: mail-certificates
  tags: mail
  roles: [domain_mail_certificate]

- hosts: mail-external
  tags: mail
  roles: [domain_mail_external]

- hosts: mail-internal
  tags: mail
  roles: [domain_mail_internal]

# 3. Web
# ------

# Plays for web service(s)

# If we're deploying web services then include the domain var for the groups of
# hosts that host web service domain roles.
- hosts: "
    database-external:reverse-proxy-external:wordpress-external:\
    wordpress-stack:dns-external:dns-internal
    "
  tags: web
  tasks:
    - ansible.builtin.include_vars:
        dir: "domains/{{ domain_name }}"
        name: domain

# If we're deploying web services then now deploy those domain roles.

# NOTE: Installs database and username used by the domain_wordpress role.
- hosts: database-external:wordpress-stack
  tags: web
  roles: [domain_wordpress_database]

- hosts: wordpress-external:wordpress-stack
  tags: web
  roles: [domain_wordpress]

- hosts: reverse-proxy-external:wordpress-stack
  tags: web
  roles: [domain_reverse_proxy]
