---

# Deploy to the dns-api host first. The mail_certificates role uses ssh-keygen
# to generate an SSH key for connecting to the host of the mail-external role
# for the purposes of deploying SSL certificates for IMAP and SMTP client
# connections. When the mail-external role is deployed it must have the
# generated public key.

- hosts: mail-certificates
  roles: [mail_certificates]

# Deploy roles where there is no inter-host dependency so all

- hosts: all
  roles: [backup_client, mta]

- hosts: backup-director
  roles: [backup_director, backup_storage]

- hosts: caldav
  roles: [calendar]

- hosts: database
  roles: [database]

- hosts: dns
  roles: [dns]

- hosts: dynamic-dns
  roles: [dynamic_dns]

- hosts: mail-external:mail-internal
  roles: [mail]

- hosts: mail-external
  roles: [mail_external]

- hosts: mail-internal
  roles: [mail_internal]

- hosts: reverse_proxy
  roles: [reverse_proxy]

- hosts: wordpress
  roles: [wordpress]
