# ------------------------------------------------------------------------------
# envs/to-be/inventory/group_vars/internal.yml
# ------------------------------------------------------------------------------

# Variables that apply to all hosts in the internal group. These are those hosts
# located on the office network.

---

# DNS clients in this group use the hub host as a nameserver
dns_client_nameservers:
  - 10.0.0.104

# The hub nameserver uses the dns-external nameserver for upstream resolution.
dns_upstream_nameservers:
  - 10.0.0.102

# Hosts on the internal network are not enabled for SSL by default.
wordpress_site_uses_ssl: false
