# ------------------------------------------------------------------------------
# envs/now/playbooks/customer/create.yml
# ------------------------------------------------------------------------------

---

# This playbook creates WordPress websites and an email service for the dummy
# domain customer.com in the now testing environment. It is a simulation of
# a playbook for a live web development project.

- hosts: web

  tasks:

    - ansible.builtin.set_fact:
        playbook_subdomains: ['dev','staging','test','www']
      tags: web

- hosts: wordpress

  tasks:

    - ansible.builtin.import_role:
        name: my_wordpress_apache
        tasks_from: create-sites
      tags: web

- hosts: dns-external

  tasks:

    - ansible.builtin.import_role:
        name: my_dynamic_dns
        tasks_from: project
      vars:
        dynamic_dns_records: "\
          {{ playbook_subdomains | intersect(project_dynamic_dns_records) }}"
      tags: web
