# my-roles/tasks/main.yml
---
- ansible.builtin.import_role:
    name: backup_client
    tasks_from: install.yml

- ansible.builtin.import_tasks:
    file: start-bacula-fd.yml

- ansible.builtin.import_role:
    name: backup_client
    tasks_from: configure.yml
