# ------------------------------------------------------------------------------
# envs/distributed/inventory/host_vars/prod1.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.101

# Backup client passwords, which of course would be sensitive data in a live
# environment.
backup_client_director_password: TKPyZEHh9NBzpMKcumaXeBdZvwZwsn68j
backup_client_monitor_password: RgqXhfvEdemarurfnbSpAeJ66ewfWr66A
