# ------------------------------------------------------------------------------
# envs/distributed/inventory/host_vars/dns-internal.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.105

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: F95SHRgJYGMpZnjKe6u5rj4Es97atgXYC
backup_client_monitor_password: TY594Lug5Ztqf55PMPJPpha4gcFVtrXNj

# The dns-internal host is a DNS service host and so can use itself for DNS
# lookups.
dns_client_nameservers:
  - 127.0.0.1
