# ------------------------------------------------------------------------------
# envs/distributed/inventory/host_vars/mail-external.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.1.103

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: PhNMsZ2Lz3Y4PE5nz6R3Vhfa5NAYYWNKN
backup_client_monitor_password: HLm9XNZG6scme88Y3AXb6KBYqTwWwREbr
