# ------------------------------------------------------------------------------
# envs/distributed/inventory/host_vars/reverse-proxy-gateway.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.113

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: Llc5J5z2Trva44QsOSalu78VJcOpwBf3q
backup_client_monitor_password: Dnr14rw5qbNKtkTUuDdQtFkEK3jfmLyqC

# The reverse-proxy-gateway host is on the internal network but it exposes
# WordPress websites externally, so it's the only internal host that's enabled
# for SSL.
host_enabled_for_ssl: yes
