# ------------------------------------------------------------------------------
# envs/distributed/inventory/host_vars/reverse-proxy-internal.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.110

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: wr2b4tSBuEAndFLY4Vft9n76Tzfz8UUMR
backup_client_monitor_password: yLrAGDhz5KwqpzTQtaMZTPjArrWXevCvR
