# ------------------------------------------------------------------------------
# my_reverse_proxy/tasks/start-nginx.yml
# ------------------------------------------------------------------------------

---

- name: Test if the nginx process is running
  ansible.builtin.shell: "\
    pgrep -f '^nginx: master process nginx -g daemon off;$' || true"
  register: pgrep_result
  changed_when: false

- name: Start the nginx process
  ansible.builtin.shell: |-
    echo 'nginx      : Starting' >> '/var/local/services.log'
    nohup nginx -g 'daemon off;' 2>&1 | sed 's/^/nginx      : /' \
      >> '/var/local/servies.log' &

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f '^nginx: master process' && \
        echo 'nginx      : Started' >> '/var/local/services.log' && break
      let n=n+1
    done

    if [ $n -eq 3 ]; then
      echo 'nginx      : Failed to start process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: not pgrep_result.stdout
