# ------------------------------------------------------------------------------
# envs/distributed/playbooks/customer/delete.yml
# ------------------------------------------------------------------------------

---

# This playbook deletes WordPress websites and an email service for the dummy
# domain customer.com in the distributed testing environment. It is a simulation
# of a playbook for a live web development project.

- hosts: wordpress-internal

  tasks:

    - block:

        - name: Check subdomains provided in --extra-vars
          ansible.builtin.debug:
            msg: >-
              If you run web tasks then you must set an extra var ("subdomains")
              containing a comma separate list of subdomains to act on; for
              example 'dev', 'dev,test', 'staging,www' etc.
          failed_when: true
          run_once: true
          when: subdomains is not defined

        - block:

            - ansible.builtin.import_role:
                name: my_dns
                tasks_from: delete-sites
              delegate_to: dns-external

            - ansible.builtin.import_role:
                name: my_reverse_proxy
                tasks_from: delete-sites
              delegate_to: reverse-proxy-gateway

          vars:
            sites_limited_to: [test, staging]

        - ansible.builtin.import_role:
            name: my_dns
            tasks_from: delete-sites
          delegate_to: dns-internal

        - ansible.builtin.import_role:
            name: my_reverse_proxy
            tasks_from: delete-sites
          delegate_to: reverse-proxy-internal

        - ansible.builtin.import_role:
            name: my_wordpress_apache
            tasks_from: delete-sites

        - ansible.builtin.import_role:
            name: my_database
            tasks_from: delete-sites
          delegate_to: database-internal

      tags: web

- hosts: wordpress-external

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: my_dns
            tasks_from: delete-sites
          delegate_to: dns-external

        - ansible.builtin.import_role:
            name: my_reverse_proxy
            tasks_from: delete-sites
          delegate_to: reverse-proxy-external

        - ansible.builtin.import_role:
            name: my_wordpress_apache
            tasks_from: delete-sites

        - ansible.builtin.import_role:
            name: my_database
            tasks_from: delete-sites
          delegate_to: database-external

      tags: web
