# ------------------------------------------------------------------------------
# envs/now/playbooks/customer/host_vars/dev1.yml
# ------------------------------------------------------------------------------

---

wordpress_sites:
  - subdomain: dev

wordpress_sites_private:
  - subdomain: dev
    admin_password: 'gCP8e86&2#^!wvQO'
    database_password: 'oF748&S*V&*U$fEo'
