# ------------------------------------------------------------------------------
# envs/live/inventory/group_vars/all/template-private.yml
# ------------------------------------------------------------------------------

# If you enable Linode integration then you will need to uncomment this line
# below and set the value of dns_linode_api_token to that of a personal access
# token that you have created for your Linode account with the required access
# rights. You might also want to rename this file to private.yml to prevent it
# being tracked by Git depending on how you're using this repository, as
# obviously your personal access token is very sensitive data.

---

#dns_linode_api_token: ...