version: "3.6"

services:

  bconsole:
    build: ./build/bconsole
    image: varilink/services/client/bconsole

  cadaver:
    build: ./build/cadaver
    image: varilink/services/client/cadaver

  dig:
    build: ./build/dig
    image: varilink/services/client/dig

  lynx:
    build: ./build/lynx
    image: varilink/services/client/lynx

  mutt:
    build: ./build/mutt
    image: varilink/services/client/mutt
