version: "3.6"

services:

  ansible:
    build: ./build/ansible
    image: varilink/services/client/ansible
    volumes: ["${PWD}:/playbooks"]

  bconsole:
    build: ./build/bconsole
    image: varilink/services/client/bconsole

  cadaver:
    build: ./build/cadaver
    image: varilink/services/client/cadaver

  dig:
    build: ./build/dig
    image: varilink/services/client/dig

  mutt:
    build: ./build/mutt
    image: varilink/services/client/mutt

  mysql:
    build: ./build/mysql
    image: varilink/services/clients/mysql
