version: "3.6"

services:

  backup-director:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_backup-director
    hostname: backup-director
    networks:
      default:
        ipv4_address: 10.0.0.101
    volumes: ["backup:/var/lib/bacula"]

  caldav:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_caldav
    hostname: caldav
    networks:
      default:
        ipv4_address: 10.0.0.102

  database-external:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_database-external
    hostname: database-external
    networks:
      default:
        ipv4_address: 10.0.0.103

  database-internal:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_database-internal
    hostname: database-internal
    networks:
      default:
        ipv4_address: 10.0.0.104

  dns-external:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_dns-external
    hostname: dns-external
    networks:
      default:
        ipv4_address: 10.0.0.105

  dns-internal:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_dns-internal
    hostname: dns-internal
    networks:
      default:
        ipv4_address: 10.0.0.106

  dynamic-dns:
    build:
      context: ./build/sshd
      args:
        RELEASE: bullseye
    image: varilink/services:bullseye
    container_name: services_dynamic-dns
    hostname: dynamic-dns
    networks:
      default:
        ipv4_address: 10.0.0.107

  email-certificates:
    build:
      context: ./build/sshd
      args:
        RELEASE: bullseye
    image: varilink/services:bullseye
    container_name: services_email-certificates
    hostname: email-certificates
    networks:
      default:
        ipv4_address: 10.0.0.108

  email-external:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_email-external
    hostname: email-external
    networks:
      default:
        ipv4_address: 10.0.0.109

  email-internal:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    hostname: email-internal
    container_name: services_email-internal
    networks:
      default:
        ipv4_address: 10.0.0.110

  reverse-proxy-external:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_reverse-proxy-external
    hostname: reverse-proxy-external
    networks:
      default:
        ipv4_address: 10.0.0.111

  reverse-proxy-internal:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_reverse-proxy-internal
    hostname: reverse-proxy-internal
    networks:
      default:
        ipv4_address: 10.0.0.112

  wordpress-external:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_wordpress-external
    hostname: wordpress-external
    networks:
      default:
        ipv4_address: 10.0.0.113

  wordpress-internal:
    build: ./build/sshd
    image: varilink/services:$RELEASE
    container_name: services_wordpress-internal
    hostname: wordpress-internal
    networks:
      default:
        ipv4_address: 10.0.0.114

volumes:

  # Required due to squashfs issue
  backup:
