version: "3.7"

# The service definitions here extend or modify those in docker/deploy.yml in
# order to bring the services up in "for test" mode as opposed to "for deploy"
# mode - see this repository's README for an explanation of this. The
# differences to "for deploy" mode are as follows:
#
# - The services here use the service specific images committed by bin/test.sh
#   rather than the generic varilink/services image that provides the sshd used
#   in "for deploy" mode.
#
# - The services here provide a service specific command to the
#   docker-entrypoint.sh script that tells that script how to bring up the
#   required service(s).
#
# - The services here define the dependencies between services that exist in
#   "for test" mode. There are no such dependencies between the services in "for
#   deploy" mode.


services:

  backup-director:
    image: varilink/services/backup-director
    depends_on: [database-internal]
    command: backup
    # Creation of Bacula MySQL tables requires that the database service is
    # ready. Since there can be a delay until that is the case, we need to
    # restart after any initial failure.
    restart: on-failure

  caldav:
    image: varilink/services/caldav
    command: caldav

  database-external:
    image: varilink/services/database-external
    command: database

  database-internal:
    image: varilink/services/database-internal
    command: database

  dns-external:
    image: varilink/services/dns-external
    command: dns

  dns-internal:
    image: varilink/services/dns-internal
    command: dns

  dynamic-dns:
    image: varilink/services/dynamic-dns
    command: dynamic-dns

  mail-certificates:
    image: varilink/services/mail-certificates
    command: mail-certificates

  mail-external:
    image: varilink/services/mail-external
    command: mail-external

  mail-internal:
    image: varilink/services/mail-internal
    command: mail-internal

  mail-other:
    image: varilink/services/mail-other
    command: mail-other

  reverse-proxy-external:
    image: varilink/services/reverse-proxy-external
    depends_on: [wordpress-external]
    command: reverse-proxy

  wordpress-external:
    image: varilink/services/wordpress-external
    depends_on: [database-external]
    command: wordpress

  wordpress-stack:
    image: varilink/services/wordpress-stack
    command: wordpress-stack
