version: "3.6"

services:

  backup-director:
    image: varilink/services/backup-director
    depends_on: [database-internal]
    command: backup
    # Creation of Bacula MySQL tables requires that the database service is
    # ready. Since there can be a delay until that is the case, we need to
    # restart after any initial failure.
    restart: on-failure

  caldav:
    image: varilink/services/caldav
    command: calendar

  database-external:
    image: varilink/services/database-external
    command: database

  database-internal:
    image: varilink/services/database-internal
    command: database

  dns-external:
    image: varilink/services/dns-external
    command: dns

  dns-internal:
    image: varilink/services/dns-internal
    command: dns

  dynamic-dns:
    image: varilink/services/dynamic-dns
    command: dynamic-dns

  email-certificates:
    image: varilink/services/email-certificates

  email-external:
    image: varilink/services/email-external
    command: email-external

  email-internal:
    image: varilink/services/email-internal
    container_name: services_email-internal
    command: email-internal

  reverse-proxy-external:
    image: varilink/services/reverse-proxy-external
    container_name: services_reverse-proxy-external
    depends_on: [wordpress-external]
    command: reverse-proxy

  reverse-proxy-internal:
    image: varilink/services/reverse-proxy-internal
    container_name: services_reverse-proxy-internal
    depends_on: [wordpress-internal]
    command: reverse-proxy

  wordpress-external:
    image: varilink/services/wordpress-external
    container_name: services_wordpress-external
    depends_on: [database-external]
    command: wordpress

  wordpress-internal:
    image: varilink/services/wordpress-internal
    container_name: services_wordpress-internal
    depends_on: [database-internal]
    command: wordpress
