# ------------------------------------------------------------------------------
# my-roles/my_dynamic_dns/tasks/start-cron.yml
# ------------------------------------------------------------------------------

---

- name: Test if the cron process is running
  ansible.builtin.shell: pgrep -f '^cron -f$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    - name: Start the cron process
      ansible.builtin.shell: |-
        echo 'cron       : Starting' >> /var/local/services.log
        nohup bash -c \
          "cron -f |& sed -u 's/^/cron       : /'" \
          &>> /var/local/services.log &
        sleep 3
      args:
        executable: /bin/bash
      become: yes

    - name: Check the cron process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |-
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^cron -f$' && \
            echo 'cron       : Started' >> /var/local/services.log && break
          let n=n+1
          sleep 3
        done
        
        if [ $n -eq 3 ]; then
          echo 'cron       : Failed to start process' \
            >> /var/local/services.log
          exit 1
        fi
      args:
        executable: /bin/bash

  when: pgrep_result.rc == 1
