# my-roles/my_mta/tasks/main.yml

---

- ansible.builtin.import_role:
    name: mta
    tasks_from: install.yml

- ansible.builtin.import_tasks:
    file: start-exim.yml

- ansible.builtin.import_role:
    name: mta
    tasks_from: configure.yml
    handlers_from: common.yml
