# ------------------------------------------------------------------------------
# my-roles/my_reverse_proxy/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: reverse_proxy
    tasks_from: install.yml

- ansible.builtin.include_tasks: start-nginx.yml

- ansible.builtin.import_role:
    name: reverse_proxy
    tasks_from: configure.yml
