# ------------------------------------------------------------------------------
# my-roles/my_reverse_proxy/tasks/stop-nginx.yml
# ------------------------------------------------------------------------------

---

- name: Test if the nginx process is running
  ansible.builtin.shell: "\
    pgrep -f '^nginx: master process nginx -g daemon off;$'"
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- name: Stop the nginx process
  ansible.builtin.shell: |-
    echo 'nginx      : Stopping' >> '/var/local/services.log'
    pkill -f '^nginx: master process'

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f '^nginx: master process' || \
        echo 'nginx      : Stopped' >> '/var/local/services.log' && break
      let n=n+1
    done
    
    if [ $n -eq 3 ]; then
      echo 'nginx      : Failed to stop process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: pgrep_result.rc == 0
