# ------------------------------------------------------------------------------
# my-roles/my_mail/tasks/stop-dovecot.yml
# ------------------------------------------------------------------------------

---

- name: Test if the dovecot process is running
  ansible.builtin.shell: pgrep -f '^/usr/sbin/dovecot -F$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- name: Stop the dovecot process
  ansible.builtin.shell: |-
    echo 'dovecot    : Stopping' >> '/var/local/services.log'
    pkill -f '^/usr/sbin/dovecot -F$'

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f "^/usr/sbin/dovecot -F$" || \
        echo 'dovecot    : Stopped' >> '/var/local/services.log' && break
      let n=n+1
    done
    
    if [ $n -eq 3 ]; then
      echo 'dovecot    : Failed to stop process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: pgrep_result.rc == 0
