# ------------------------------------------------------------------------------
# envs/to-be/inventory/host_vars/gateway.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.103

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: bvKY1w1jkxapj2QReP1vubEKaYW0t1wx2
backup_client_monitor_password: Pb3y7Il7wbyXHs9HiAIzEUTlbHQMTivle

# The gateway host is on the internal network but it exposes WordPress websites
# externally, so it's the only internal host that's enabled for SSL.
host_enabled_for_ssl: yes
