# ------------------------------------------------------------------------------
# envs/to-be/inventory/host_vars/hub.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.0.104

# Backup client passwords, which of course would be sensitive data in a true,
# live environment.
backup_client_director_password: iT92n5zyJL2O67pgrPiJKAUTLs7akG67Y
backup_client_monitor_password: b3X9R32uhKw7BrcFbVtOvAwOs7aJ5ZW6g

# The hub host is a DNS service host and so can use itself for DNS lookups.
dns_client_nameservers:
  - 127.0.0.1
