# ------------------------------------------------------------------------------
# my_roles/my_backup_director/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: my_mta

- ansible.builtin.import_role:
    name: backup_director
    tasks_from: install

- ansible.builtin.import_role:
    name: backup_director
    tasks_from: catalog

- ansible.builtin.import_role:
    name: backup_director
    tasks_from: configure
