# ------------------------------------------------------------------------------
# my-roles/my_backup_director/tasks/start-bacula-dir.yml
# ------------------------------------------------------------------------------

---

- name: Test if the bacula-dir process is running
  ansible.builtin.shell: pgrep -f '^bacula-dir -f$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    # If I introduce a nested block here for the common 'become: yes' on the
    # next two tasks, then I get an error with the following message:
    #
    # ERROR! Unexpected Exception, this is probably a bug:
    # 'Block' object has no attribute 'get_name'

    - name: Create the /run/bacula directory
      ansible.builtin.file:
        path: /run/bacula
        state: directory
      become: yes

    - name: Start the bacula-dir process
      ansible.builtin.shell: |-
        echo 'bacula-dir : Starting' >> /var/local/services.log
        nohup bash -c \
          "bacula-dir -f |& sed -u 's/^\(bacula-dir: \)\?/bacula-dir : /'" \
          &>> /var/local/services.log &
        sleep 3
      args:
        executable: /bin/bash
      become: yes

    - name: Check the bacula-dir process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |-
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^bacula-dir -f$' && \
            echo 'bacula-dir : Started' >> /var/local/services.log && break
          let n=n+1
          sleep 3
        done

        if [ $n -eq 3 ]; then
          echo 'bacula-dir : Failed to start process' \
            >> /var/local/services.log
          exit 1
        fi
      args:
        executable: /bin/bash

  when: pgrep_result.rc == 1
