# my-roles/my_dns/tasks/main.yml

---

- ansible.builtin.import_role:
    name: dns
    tasks_from: install.yml
    handlers_from: none.yml

- ansible.builtin.import_tasks: start-dnsmasq.yml

- ansible.builtin.import_role:
    name: dns
    tasks_from: configure.yml
    handlers_from: none.yml
