ansible_host: 10.0.0.114

backup_client_director_password: ppm4teJeQwfnANBVQWqLWYjbBqx6XDr9c
backup_client_monitor_password: Vb8fAAAuPm9TrhU4yQCCUVCMR8kP9VdXR

reverse_proxy_uses_ssl: false

wordpress_ports:
  - 8080 # test.varilink.co.uk
  - 8081 # dev.client.com
  - 8082 # test.client.com
