ansible_host: 10.0.0.113

backup_client_director_password: GKLwgpLjqrFFMTH5NMR9DFMdwDqrwVpgw
backup_client_monitor_password: gCzjzV6Amkz9S9uTFm8mM6ky5ks9f2Dz9

wordpress_expose_externally: true
wordpress_ports:
  - 8080 # www.varilink.co.uk
  - 8081 # www.client.com
