# ------------------------------------------------------------------------------
# my-roles/my_dns_client/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: dns_client
  vars:
    unsafe_writes: true
