# ------------------------------------------------------------------------------
# my-roles/my_dynamic_dns/tasks/project.yml
# ------------------------------------------------------------------------------

# A spoofing of the creation of dynamic DNS entries that happens via Linode API
# integration in a true live environment. In our test environments the same
# effect is achieved by adding DNS entries to the host that simulates our ISP's
# DNS service.

---

  - ansible.builtin.import_role:
      name: my_dns
      tasks_from: none

  - ansible.builtin.lineinfile:
      path: /etc/addn-hosts
      line: 10.0.1.254 {{ item + '.' + domain_name }}
      regexp: >-
        ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
        {{ item + '.' + domain_name | regex_escape() }}$
    loop: "{{ dynamic_dns_records }}"
    notify: Dnsmasq configuration changed
    become: yes
