name: customer.com
organisation: Mock-Up Customer Organisation

# Default reverse proxy pass port to use when configuring this domain's web
# services. This can be overridden for an individual webhost below.
reverse_proxy_pass_port: 8081

# Details of each webhost that a web service for which a web service is to be
# deployed for this domain.
webhosts:
  - name: dev
    reverse_proxy_host: wordpress-stack-internal
    wordpress_host: wordpress-stack-internal
    wordpress_database_host: wordpress-stack-internal
    wordpress_database_password: 'z!dhn4vmJbe$N_JJ'
  - name: test
    reverse_proxy_host: wordpress-stack-internal
    reverse_proxy_pass_port: 8082
    wordpress_host: wordpress-stack-internal
    wordpress_database_host: wordpress-stack-internal
    wordpress_database_password: 'KD_y2Q*&*Ca-XLt@'
  - name: www
    reverse_proxy_host: reverse-proxy-external
    wordpress_host: wordpress-external
    wordpress_database_host: database-external
    wordpress_database_password: '*AtEz?dpfg^m3aw@'

# Details for Dynamic DNS updates for this domain.
linode_domain_id: 1878505
linode_dynamic_dns_domain_records:
  - 21912263 # test

# Users for which to configure a mail service for this domain.
users:
  # A personal email address in the form userfname.userlname
  - email: userfname.userlname
    passwd: userpasswd
  # A role (e.g. 'chair') in the form rolename
  - email: rolename
    passwd: rolepasswd
