# ------------------------------------------------------------------------------
# my-roles/my_database/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: database
    tasks_from: install.yml

- ansible.builtin.include_tasks: start-mysql.yml

- ansible.builtin.import_role:
    name: database
    tasks_from: configure.yml
