# ------------------------------------------------------------------------------
# my-roles/my_mail_external/tasks/domain.yml
# ------------------------------------------------------------------------------

---

# Import my_mta role for its "Exim configuration changed" handlers.
- ansible.builtin.import_role:
    name: my_mta
    tasks_from: none.yml

# Import my_mail role for its "Dovecot configuration changed" handlers.
- ansible.builtin.import_role:
    name: my_mail
    tasks_from: none.yml

- ansible.builtin.import_role:
    name: mail_external
    tasks_from: domain
    vars_from: none
