#-------------------------------------------------------------------------------
# Ansible connection variables and arguments
#-------------------------------------------------------------------------------

ansible_host: 10.0.0.102

#-------------------------------------------------------------------------------
# Variables used by the roles in my Libraries - Ansible repository
# See the README for that repository at:
# https://github.com/varilink/libraries-ansible#readme
# for documentation about these variables.
#-------------------------------------------------------------------------------

# Mandatory
# ---------

backup_client_director_password: LzhEdwd3U7n59yWe2RVnwPXsRdV87KHME
backup_client_monitor_password: 4rRLA5CBsPH2LPYJ8yDg5zzt87jUzQKLp
