# ------------------------------------------------------------------------------
# my-roles/my_wordpress_nginx/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: my_wordpress

- ansible.builtin.import_role:
    name: wordpress_nginx
    tasks_from: install
    handlers_from: none.yml

- ansible.builtin.import_tasks: start-php-fpm.yml

- ansible.builtin.import_tasks: start-nginx.yml

- ansible.builtin.import_role:
    name: wordpress_nginx
    tasks_from: configure
    handlers_from: none
