# ------------------------------------------------------------------------------
# my-roles/my_wordpress_nginx/tasks/start-nginx.yml
# ------------------------------------------------------------------------------

---

- name: Test if the nginx process is running
  ansible.builtin.shell: |-
    pgrep -f '^nginx: master process nginx -g daemon off;$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    - name: Start the nginx process
      ansible.builtin.shell: |-
        echo 'nginx      : Starting' >> '/var/local/services.log'
        nohup bash -c \
          "nginx -g 'daemon off;' |& sed -u 's/^/nginx      : /'" \
          &>> '/var/local/servies.log' &
        sleep 3
      args:
        executable: /bin/bash
      become: yes

    - name: Check the nginx process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |-
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^nginx: master process' && \
            echo 'nginx      : Started' >> '/var/local/services.log' && break
          let n=n+1
          sleep 3
        done
        
        if [ $n -eq 3 ]; then
          echo 'nginx      : Failed to start process' \
            >> /var/local/services.log
          exit 1
        fi
      args:
        executable: /bin/bash

  when: not pgrep_result.stdout
